import express from "express";
import soap from "soap";
import axios from "axios"; // Added missing import
import { config } from 'dotenv';
import { prisma } from "../config/db.js";
config();

const refundRequest = async (req, res) => {
    const { shortCode, orderId, firstName, lastName, amount, currency, ReferenceNumber, refundFOP, refundReferenceCode } = req.body;

    // Check CBS Trn and if there is reverse else return failure reason
    const cbs_sucess = true;
    const responce = "";
    if (cbs_sucess) {
        return res.status(200).json({
            "ResponseCode": 1,
            "success": "Success",
            "ResponseCodeDescription": "Successfully accepted Refund request"
        });
    } else {
        return res.status(200).json({
            "ResponseCode": 0,
            "ResponseCodeDescription": "There is no any transaction associated with this {ReferenceNumber}",
            "Status": "Error"
        });
    }


};




// const CBS_URL = "http://10.1.22.100:7003/FCUBSAccService/FCUBSAccService?WSDL"; 

// const confirmOrder = async (req, res) => {
//     const { orderid, amount, beneficiaryAcno, remark } = req.body;

//     try {
//         // --- 1. CBS Interaction (Oracle Flexcube SOAP Call) ---
//         const soapClient = await soap.createClientAsync(CBS_URL);
        
//         // Constructing the header based on Web.config requirements 
//         const cbsHeader = {
//             SOURCE: "ADC", // From Header_Source 
//             USERID: "ADCUSER", // From Header_UserID 
//             BRANCH: "004", // From Header_Branch 
//             SERVICE: "FCUBSAccService",
//             OPERATION: "CreateTransaction"
//         };

//         const cbsBody = {
//             // Mapping fields to the Flexcube account service requirements
//             CUSTACNO: beneficiaryAcno,
//             LCYAMOUNT: amount,
//             REMARK: remark
//         };

//         // Execute CBS Debit/Credit
//         const [cbsResult] = await soapClient.CreateTransactionAsync({ FCUBS_HEADER: cbsHeader, FCUBS_BODY: cbsBody });
        
//         // Assume cbsResult contains a unique 'ReferenceNumber' on success
//         const cbsRef = cbsResult.REFERENCE_NO;

//         // --- 2. Send Data to FlyGate (Airline) ---
//         // Based on the provided image documentation for "Confirm Order (Confirm Payment)"
//         const flyGatePayload = {
//             Header: "Basic AUTH_TOKEN", 
//             OrderId: orderid,
//             shortCode: process.env.shortCodeT,
//             Amount: amount,
//             Currency: "ETB",
//             Status: 1, // 1 = Success
//             Remark: "Successfully Paid",
//             TraceNumber: `TRC${Date.now()}`, // Unique Ethiopian Gateway number
//             ReferenceNumber: cbsRef, // Unique bank reference from CBS
//             PaidAccountNumber: beneficiaryAcno,
//             PayerCustomerName: req.body.customerName || "Enat Customer"
//         };

//         const flyGateResponse = await axios.post(
//             `${process.env.url}/Enat/api/V1.0/Enat/ConfirmOrder`, 
//             flyGatePayload
//         );

//         // --- 3. Return Final Response to your Frontend ---
//         return res.json({
//             status: "Success",
//             message: "Transaction and FlyGate confirmation complete",
//             cbsReference: cbsRef,
//             flyGateData: flyGateResponse.data
//         });

//     } catch (error) {
//         console.error("Transaction Error:", error);
//         return res.status(500).json({
//             status: "Error",
//             message: "Transaction failed",
//             error: error.message
//         });
//     }
// };

// const confirmOrder = async (req, res) => {
//     const { beneficiaryAcno, amount, cbsRef, remark } = req.body;

//     try {
//         // 1. Validate Request (Check if account and amount are present)
        
//         // // CBS Interaction here.
//         // This is where you call your internal Banking SOAP/REST API to:
//         // - Verify the account exists and is active.
//         // - Check if the account has sufficient balance.
//         // - Perform the actual debit/credit (Move the money).
//         // - Receive a unique transaction reference from the bank.

//         // 2. Notify FlyGate (Only if CBS transaction was successful)
//         const response = await axios.post(`${url}/Enat/api/V1.0/Enat/ConfirmOrder`, {
//             account: beneficiaryAcno,
//             amount: amount,
//             reference: cbsRef, // Usually the reference generated by your CBS
//             remark: remark
//         });

//         return res.json({
//             status: "Success",
//             message: "Successfully transferred",
//             reference: cbsRef
//         });

//     } catch (error) {
//         // 3. Error Handling (Rollback or notify failure)
//         return res.status(500).json({
//             status: "Error",
//             message: "Transaction failed during CBS or FlyGate sync",
//             error: error.message
//         });
//     }

// };

